// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Payments API",
    "title": "PaymentsSimple application",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "list payments",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      },
      "post": {
        "summary": "create payment",
        "parameters": [
          {
            "description": "The payment to create",
            "name": "payment",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    },
    "/fetch": {
      "get": {
        "summary": "fetch/import payments from source",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    },
    "/ping": {
      "get": {
        "summary": "ping service",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "summary": "get payment",
        "parameters": [
          {
            "$ref": "#/parameters/payment_id"
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      },
      "delete": {
        "summary": "delete payment",
        "parameters": [
          {
            "$ref": "#/parameters/payment_id"
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      },
      "patch": {
        "summary": "patch payment",
        "parameters": [
          {
            "$ref": "#/parameters/payment_id"
          },
          {
            "description": "payment patch body",
            "name": "payment",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "$ref": "#/responses/Error"
          }
        }
      }
    }
  },
  "definitions": {
    "attributes": {
      "type": "object",
      "required": [
        "amount",
        "currency",
        "reference"
      ],
      "properties": {
        "amount": {
          "type": "string",
          "minLength": 1
        },
        "currency": {
          "type": "string",
          "minLength": 1
        },
        "reference": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "attributes"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/attributes"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "organisation_id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "integer"
        }
      }
    }
  },
  "parameters": {
    "payment_id": {
      "type": "string",
      "format": "uuid",
      "description": "Payment ID",
      "name": "id",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "Error": {
      "description": "generic error",
      "schema": {
        "$ref": "#/definitions/message"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Payments API",
    "title": "PaymentsSimple application",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "list payments",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      },
      "post": {
        "summary": "create payment",
        "parameters": [
          {
            "description": "The payment to create",
            "name": "payment",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/fetch": {
      "get": {
        "summary": "fetch/import payments from source",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "summary": "ping service",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "summary": "get payment",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Payment ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      },
      "delete": {
        "summary": "delete payment",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Payment ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      },
      "patch": {
        "summary": "patch payment",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Payment ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "payment patch body",
            "name": "payment",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "attributes": {
      "type": "object",
      "required": [
        "amount",
        "currency",
        "reference"
      ],
      "properties": {
        "amount": {
          "type": "string",
          "minLength": 1
        },
        "currency": {
          "type": "string",
          "minLength": 1
        },
        "reference": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "attributes"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/attributes"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "organisation_id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "integer"
        }
      }
    }
  },
  "parameters": {
    "payment_id": {
      "type": "string",
      "format": "uuid",
      "description": "Payment ID",
      "name": "id",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "Error": {
      "description": "generic error",
      "schema": {
        "$ref": "#/definitions/message"
      }
    }
  }
}`))
}
