// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Payments API",
    "title": "PaymentsSimple application",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "description": "list payments operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/fetch": {
      "get": {
        "responses": {
          "200": {
            "description": "fetch payments from source",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "responses": {
          "200": {
            "description": "ping service",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "attributes": {
      "type": "object",
      "required": [
        "amount",
        "currency",
        "reference"
      ],
      "properties": {
        "amount": {
          "type": "string",
          "minLength": 1
        },
        "currency": {
          "type": "string",
          "minLength": 1
        },
        "reference": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "attributes"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/attributes"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "organisation_id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "integer"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Payments API",
    "title": "PaymentsSimple application",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "description": "list payments operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/fetch": {
      "get": {
        "responses": {
          "200": {
            "description": "fetch payments from source",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "responses": {
          "200": {
            "description": "ping service",
            "schema": {
              "$ref": "#/definitions/message"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "attributes": {
      "type": "object",
      "required": [
        "amount",
        "currency",
        "reference"
      ],
      "properties": {
        "amount": {
          "type": "string",
          "minLength": 1
        },
        "currency": {
          "type": "string",
          "minLength": 1
        },
        "reference": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "attributes"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/attributes"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "organisation_id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "integer"
        }
      }
    }
  }
}`))
}
