// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetFetchHandlerFunc turns a function with the right signature into a get fetch handler
type GetFetchHandlerFunc func(GetFetchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFetchHandlerFunc) Handle(params GetFetchParams) middleware.Responder {
	return fn(params)
}

// GetFetchHandler interface for that can handle valid get fetch params
type GetFetchHandler interface {
	Handle(GetFetchParams) middleware.Responder
}

// NewGetFetch creates a new http.Handler for the get fetch operation
func NewGetFetch(ctx *middleware.Context, handler GetFetchHandler) *GetFetch {
	return &GetFetch{Context: ctx, Handler: handler}
}

/*GetFetch swagger:route GET /fetch getFetch

GetFetch get fetch API

*/
type GetFetch struct {
	Context *middleware.Context
	Handler GetFetchHandler
}

func (o *GetFetch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFetchParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
