// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	models "payments-simple/internal/pkg/rest/models"

	"github.com/go-openapi/runtime"
)

// PatchIDOKCode is the HTTP code returned for type PatchIDOK
const PatchIDOKCode int = 200

/*PatchIDOK success

swagger:response patchIdOK
*/
type PatchIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Payment `json:"body,omitempty"`
}

// NewPatchIDOK creates PatchIDOK with default headers values
func NewPatchIDOK() *PatchIDOK {

	return &PatchIDOK{}
}

// WithPayload adds the payload to the patch Id o k response
func (o *PatchIDOK) WithPayload(payload []*models.Payment) *PatchIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch Id o k response
func (o *PatchIDOK) SetPayload(payload []*models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Payment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PatchIDDefault generic error

swagger:response patchIdDefault
*/
type PatchIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewPatchIDDefault creates PatchIDDefault with default headers values
func NewPatchIDDefault(code int) *PatchIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch ID default response
func (o *PatchIDDefault) WithStatusCode(code int) *PatchIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch ID default response
func (o *PatchIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch ID default response
func (o *PatchIDDefault) WithPayload(payload *models.Message) *PatchIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch ID default response
func (o *PatchIDDefault) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
