consumes:
- application/json
info:
  description: Payments API
  title: PaymentsSimple application
  version: 0.0.1
produces:
- application/json
schemes:
- http
swagger: "2.0"

definitions:
  payment:
    type: object
    required:
      - attributes
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      type:
        type: string
        #minLength: 1
      organisation_id:
        type: string
        format: uuid
        readOnly: true
      version:
        type: integer
      attributes:
        $ref: "#/definitions/attributes"

  attributes: 
    type: object
    required:
      - amount
      - currency
      - reference
    properties:
      amount:
        type: string
        minLength: 1
      currency:
        type: string
        minLength: 1
      reference:
        type: string
        minLength: 1

  message:
    type: object
    required:
      - message
    properties:
      message:
        type: string

parameters:
  payment_id:
    name: id
    in: path
    description: Payment ID
    required: true
    type: string
    format: uuid

responses:
  Error:
    description: generic error
    schema:
      $ref: "#/definitions/message"

paths:
  /ping:
    get:
      summary: ping service
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/message"
        default:
          $ref: "#/responses/Error"
  /:
    get:
      summary: list payments
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/payment"
        default:
          $ref: "#/responses/Error"
    post:
      summary: create payment
      parameters:
        - in: body
          name: payment
          description: The payment to create
          schema:
            $ref: "#/definitions/payment"
      responses:
        201:
          description: created
        default:
          $ref: "#/responses/Error"
  /{id}:
    get:
      summary: get payment
      parameters:
        - $ref: "#/parameters/payment_id"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/payment"
        default:
          $ref: "#/responses/Error"
    patch:
      summary: patch payment
      parameters:
        - $ref: "#/parameters/payment_id"
        - in: body
          name: payment
          description: payment patch body
          schema:
            $ref: "#/definitions/payment"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/payment"
        default:
          $ref: "#/responses/Error"
    delete:
      summary: delete payment
      parameters:
        - $ref: "#/parameters/payment_id"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/payment"
        default:
          $ref: "#/responses/Error"
  /fetch:
    get:
      summary: fetch/import payments from source
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/message"
        default:
          $ref: "#/responses/Error"
